### ISSUE TITLE
i18n: Improve our i18n integration

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1478]
### Description

Since we added our initial i18n integration a few things have been added/come to light, so I'd like to use this as a general issue to improve this slightly.

1. [X] `@kong-ui-public/i18n` have added configurable errors for us, so we should be able to use that instead of rolling our own.
2. [x] `formatjs` seems to throw when a translation key is an empty string. There are uncommon random usecase where we might want to use an empty string, if we are looking at the error config this (point 1) we may as well look at this also.
3. [x] ~Instead of using `env` for "i18n global variables", we should just use i18n for a group of select `i18n` keys that we define as being available "globally". We can collect these "globals" at i18n service start up (using `@kong-ui-public/i18n#t` and then always feed them into our own `t`). In doing this we remove the dependency on `env` and then we should be closer to only having a single place for defining application strings.~ Replaced by https://github.com/kumahq/kuma-gui/issues/2431
4. [x] ~I'd like to integrate and perhaps use the `<I18nT />` component, it requires extra setup so I'd like to do that so at least it available as and when we need it.~ Replaced by https://github.com/kumahq/kuma-gui/issues/2429
5. [x] ~Use auto-prefixes (so we don't need to pass long keys to i18n).~ Replaced by https://github.com/kumahq/kuma-gui/issues/2430

**Comment by lahabana** [comment]
What's the relationship of this issue with: https://github.com/kumahq/kuma-gui/pull/1537 ?

**Comment by johncowen** [comment]
That would be point 4 from the PR desc:

> 4. I'd like to integrate and perhaps use the <I18nT /> component, it requires extra setup so I'd like to do that so at least it available as and when we need it.

So, Point 4 above (the integration bit) is solved via https://github.com/kumahq/kuma-gui/pull/1537, we don't use `<I18nT />` yet.

I also noticed that we can't use it with our in YAML i18n markdown as yet because `<I18nT />` escapes any HTML and there isn't yet a way to turn that off. If we wanted to add and upstream that, that could be looked at as part of this issue.

**Comment by lahabana** [comment]
@johncowen to split this in smaller issues

**Comment by johncowen** [comment]
I've split this up and updated the description with links to the PRs that have been split off for each individual issue.

Closing this one.
